<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MenuItem;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ads = [
            ['id' => 79, 'parent_key' => 72, 'order' => 79, 'key' => 'gift_cards', 'route' => 'admin.finance.gifts', 'route_slug' => NULL, 'label' => 'Gift Cards', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 80, 'parent_key' => 72, 'order' => 80, 'key' => 'referral_system', 'route' => 'admin.referral.settings', 'route_slug' => NULL, 'label' => 'Referral System', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 81, 'parent_key' => 72, 'order' => 81, 'key' => 'referral_payouts', 'route' => 'admin.referral.payouts', 'route_slug' => NULL, 'label' => 'Referral Payouts', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 82, 'parent_key' => 72, 'order' => 82, 'key' => 'invoice_settings', 'route' => 'admin.settings.invoice', 'route_slug' => NULL, 'label' => 'Invoice Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 83, 'parent_key' => 72, 'order' => 83, 'key' => 'payment_settings', 'route' => 'admin.finance.settings', 'route_slug' => NULL, 'label' => 'Finance Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 84, 'parent_key' => NULL, 'order' => 84, 'key' => 'support_requests', 'route' => 'admin.support', 'route_slug' => NULL, 'label' => 'Support Requests', 'icon' => 'fa-solid fa-message-question', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 85, 'parent_key' => NULL, 'order' => 85, 'key' => 'email_notifications', 'route' => NULL, 'route_slug' => NULL, 'label' => 'Email & Notifications', 'icon' => 'fa-solid fa-envelope-circle-check', 'type' => 'group', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 86, 'parent_key' => 85, 'order' => 86, 'key' => 'newsletter', 'route' => 'admin.email.newsletter', 'route_slug' => NULL, 'label' => 'Newsletter', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 87, 'parent_key' => 85, 'order' => 87, 'key' => 'email_templates', 'route' => 'admin.email.templates', 'route_slug' => NULL, 'label' => 'Email Templates', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 88, 'parent_key' => 85, 'order' => 88, 'key' => 'mass_notifications', 'route' => 'admin.notifications', 'route_slug' => NULL, 'label' => 'Mass Notifications', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 89, 'parent_key' => 85, 'order' => 89, 'key' => 'system_notifications', 'route' => 'admin.notifications.system', 'route_slug' => NULL, 'label' => 'System Notifications', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 90, 'parent_key' => NULL, 'order' => 90, 'key' => 'frontend_management', 'route' => NULL, 'route_slug' => NULL, 'label' => 'Frontend Management', 'icon' => 'fa-solid fa-earth-americas', 'type' => 'group', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 91, 'parent_key' => 90, 'order' => 91, 'key' => 'frontend_settings', 'route' => 'admin.settings.frontend', 'route_slug' => NULL, 'label' => 'Frontend Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 92, 'parent_key' => 90, 'order' => 92, 'key' => 'frontend_sections', 'route' => 'admin.settings.section', 'route_slug' => NULL, 'label' => 'Frontend Sections', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 93, 'parent_key' => 90, 'order' => 93, 'key' => 'seo_management', 'route' => 'admin.settings.seo', 'route_slug' => NULL, 'label' => 'SEO Manager', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 94, 'parent_key' => 90, 'order' => 94, 'key' => 'pages', 'route' => 'admin.settings.page', 'route_slug' => NULL, 'label' => 'Pages', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 95, 'parent_key' => 90, 'order' => 95, 'key' => 'logos', 'route' => 'admin.settings.appearance', 'route_slug' => NULL, 'label' => 'Logos', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 96, 'parent_key' => 90, 'order' => 96, 'key' => 'how_it_works_section', 'route' => 'admin.settings.step', 'route_slug' => NULL, 'label' => 'How it Works Section', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 97, 'parent_key' => 90, 'order' => 97, 'key' => 'use_cases_section', 'route' => 'admin.settings.case', 'route_slug' => NULL, 'label' => 'Use Cases Section', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 98, 'parent_key' => 90, 'order' => 98, 'key' => 'ai_tools_section', 'route' => 'admin.settings.tool', 'route_slug' => NULL, 'label' => 'AI Tools Section', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 99, 'parent_key' => 90, 'order' => 99, 'key' => 'features_section', 'route' => 'admin.settings.feature', 'route_slug' => NULL, 'label' => 'Features Section', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 100, 'parent_key' => 90, 'order' => 100, 'key' => 'clients_section', 'route' => 'admin.settings.client', 'route_slug' => NULL, 'label' => 'Clients Section', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 101, 'parent_key' => 90, 'order' => 101, 'key' => 'reviews_manager', 'route' => 'admin.settings.review', 'route_slug' => NULL, 'label' => 'Reviews Manager', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 102, 'parent_key' => 90, 'order' => 102, 'key' => 'blogs_manager', 'route' => 'admin.settings.blog', 'route_slug' => NULL, 'label' => 'Blogs Manager', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 103, 'parent_key' => 90, 'order' => 103, 'key' => 'faq_manager', 'route' => 'admin.settings.faq', 'route_slug' => NULL, 'label' => 'FAQs Manager', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 104, 'parent_key' => 90, 'order' => 104, 'key' => 'google_adsense', 'route' => 'admin.settings.adsense', 'route_slug' => NULL, 'label' => 'Google Adsense', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 105, 'parent_key' => NULL, 'order' => 105, 'key' => 'general_settings', 'route' => NULL, 'route_slug' => NULL, 'label' => 'General Settings', 'icon' => 'fa fa-sliders', 'type' => 'group', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 106, 'parent_key' => 105, 'order' => 106, 'key' => 'global_settings', 'route' => 'admin.settings.global', 'route_slug' => NULL, 'label' => 'Global Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 107, 'parent_key' => 105, 'order' => 107, 'key' => 'auth_settings', 'route' => 'admin.settings.oauth', 'route_slug' => NULL, 'label' => 'Auth Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 108, 'parent_key' => 105, 'order' => 108, 'key' => 'registration_settings', 'route' => 'admin.settings.registration', 'route_slug' => NULL, 'label' => 'Registration Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 109, 'parent_key' => 105, 'order' => 109, 'key' => 'smtp_settings', 'route' => 'admin.settings.smtp', 'route_slug' => NULL, 'label' => 'SMTP Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 110, 'parent_key' => 105, 'order' => 110, 'key' => 'gdpr_settings', 'route' => 'admin.settings.gdpr', 'route_slug' => NULL, 'label' => 'GDPR Cookies', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 111, 'parent_key' => 105, 'order' => 111, 'key' => 'languages', 'route' => 'elseyyid.translations.home2', 'route_slug' => NULL, 'label' => 'Languages', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 112, 'parent_key' => 105, 'order' => 112, 'key' => 'system_settings', 'route' => 'admin.settings.system', 'route_slug' => NULL, 'label' => 'System Settings', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 113, 'parent_key' => 105, 'order' => 113, 'key' => 'activation', 'route' => 'admin.settings.activation', 'route_slug' => NULL, 'label' => 'Activation', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 114, 'parent_key' => 105, 'order' => 114, 'key' => 'upgrade_software', 'route' => 'admin.settings.upgrade', 'route_slug' => NULL, 'label' => 'Upgrade Software', 'icon' => 'fa-solid fa-angles-right', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 115, 'parent_key' => NULL, 'order' => 115, 'key' => 'menu_builder', 'route' => 'admin.davinci.configs.menu', 'route_slug' => NULL, 'label' => 'Menu Builder', 'icon' => 'fa-solid fa-bars', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 1, 'extension' => 0, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
            ['id' => 116, 'parent_key' => NULL, 'order' => 116, 'key' => 'ai_speech_to_text_pro', 'route' => 'user.extension.speech.pro', 'route_slug' => NULL, 'label' => 'Speech to Text Pro', 'icon' => 'fa-solid fa-microphone', 'type' => 'item', 'svg' => NULL, 'is_active' => 1, 'is_admin' => 0, 'extension' => 1, 'url' => NULL, 'permission' => NULL, 'conditions' => [], 'badge_text' => NULL, 'badge_type' => NULL, 'children' => [], 'original' => 1],
        ];  

        foreach ($ads as $ad) {
            MenuItem::updateOrCreate(['id' => $ad['id']], $ad);
        }
    }
}
