<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Voice;

class VoicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $voices = [                                  
            ['id' => 3603, 'voice' => 'Omar', 'voice_id' => 'ar-MS_OmarVoice', 'gender' => 'Male', 'language_code' => 'ar-XA', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/omar.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/32.jpg'],
            ['id' => 3604, 'voice' => 'LiNa', 'voice_id' => 'zh-CN_LiNaVoice', 'gender' => 'Female', 'language_code' => 'zh-CN', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/lina.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/6.jpg'],
            ['id' => 3605, 'voice' => 'WangWei', 'voice_id' => 'zh-CN_WangWeiVoice', 'gender' => 'Male', 'language_code' => 'zh-CN', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/wangwei.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/33.jpg'],
            ['id' => 3606, 'voice' => 'ZhangJing', 'voice_id' => 'zh-CN_ZhangJingVoice', 'gender' => 'Female', 'language_code' => 'zh-CN', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/zhangjing.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/7.jpg'],
            ['id' => 3607, 'voice' => 'Emma', 'voice_id' => 'nl-NL_EmmaVoice', 'gender' => 'Female', 'language_code' => 'nl-NL', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/emma.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/8.jpg'],
            ['id' => 3608, 'voice' => 'Liam', 'voice_id' => 'nl-NL_LiamVoice', 'gender' => 'Male', 'language_code' => 'nl-NL', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/liam.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/34.jpg'],
            ['id' => 3609, 'voice' => 'Craig', 'voice_id' => 'en-AU_CraigVoice', 'gender' => 'Male', 'language_code' => 'en-AU', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/craig.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/35.jpg'],
            ['id' => 3610, 'voice' => 'Madison', 'voice_id' => 'en-AU_MadisonVoice', 'gender' => 'Female', 'language_code' => 'en-AU', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/madison.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/10.jpg'],
            ['id' => 3611, 'voice' => 'Charlotte', 'voice_id' => 'en-GB_CharlotteV3Voice', 'gender' => 'Female', 'language_code' => 'en-GB', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/charlotte.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/11.jpg'],
            ['id' => 3612, 'voice' => 'James', 'voice_id' => 'en-GB_JamesV3Voice', 'gender' => 'Male', 'language_code' => 'en-GB', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/james.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/36.jpg'],
            ['id' => 3613, 'voice' => 'Kate', 'voice_id' => 'en-GB_KateV3Voice', 'gender' => 'Female', 'language_code' => 'en-GB', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/kate.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/12.jpg'],
            ['id' => 3614, 'voice' => 'Allison', 'voice_id' => 'en-US_AllisonV3Voice', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/alison.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/13.jpg'],
            ['id' => 3615, 'voice' => 'Emily', 'voice_id' => 'en-US_EmilyV3Voice', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/emily.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/14.jpg'],
            ['id' => 3616, 'voice' => 'Henry', 'voice_id' => 'en-US_HenryV3Voice', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/henry.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/37.jpg'],
            ['id' => 3617, 'voice' => 'Kevin', 'voice_id' => 'en-US_KevinV3Voice', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/kevin.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/38.jpg'],
            ['id' => 3618, 'voice' => 'Lisa', 'voice_id' => 'en-US_LisaV3Voice', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/lisa.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/15.jpg'],
            ['id' => 3619, 'voice' => 'Michael', 'voice_id' => 'en-US_MichaelV3Voice', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/michael.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/39.jpg'],
            ['id' => 3620, 'voice' => 'Olivia', 'voice_id' => 'en-US_OliviaV3Voice', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/olivia.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/16.jpg'],
            ['id' => 3621, 'voice' => 'Nicolas', 'voice_id' => 'fr-FR_NicolasV3Voice', 'gender' => 'Male', 'language_code' => 'fr-FR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/nicolas.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/40.jpg'],
            ['id' => 3622, 'voice' => 'Renee', 'voice_id' => 'fr-FR_ReneeV3Voice', 'gender' => 'Female', 'language_code' => 'fr-FR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/renee.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/17.jpg'],
            ['id' => 3624, 'voice' => 'Birgit', 'voice_id' => 'de-DE_BirgitV3Voice', 'gender' => 'Female', 'language_code' => 'de-DE', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/brigit.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/18.jpg'],
            ['id' => 3625, 'voice' => 'Dieter', 'voice_id' => 'de-DE_DieterV3Voice', 'gender' => 'Male', 'language_code' => 'de-DE', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/dieter.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/21.jpg'],
            ['id' => 3626, 'voice' => 'Erika', 'voice_id' => 'de-DE_ErikaV3Voice', 'gender' => 'Female', 'language_code' => 'de-DE', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/erika.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/19.jpg'],
            ['id' => 3627, 'voice' => 'Francesca', 'voice_id' => 'it-IT_FrancescaV3Voice', 'gender' => 'Female', 'language_code' => 'it-IT', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/francesca.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/20.jpg'],
            ['id' => 3628, 'voice' => 'Emi', 'voice_id' => 'ja-JP_EmiV3Voice', 'gender' => 'Female', 'language_code' => 'ja-JP', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/emi.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/1.jpg'],
            ['id' => 3629, 'voice' => 'Hyunjun', 'voice_id' => 'ko-KR_HyunjunVoice', 'gender' => 'Male', 'language_code' => 'ko-KR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/hyunjun.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/22.jpg'],
            ['id' => 3630, 'voice' => 'SiWoo', 'voice_id' => 'ko-KR_SiWooVoice', 'gender' => 'Male', 'language_code' => 'ko-KR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/siwoo.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/23.jpg'],
            ['id' => 3631, 'voice' => 'Youngmi', 'voice_id' => 'ko-KR_YoungmiVoice', 'gender' => 'Female', 'language_code' => 'ko-KR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/youngmi.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/2.jpg'],
            ['id' => 3632, 'voice' => 'Yuna', 'voice_id' => 'ko-KR_YunaVoice', 'gender' => 'Female', 'language_code' => 'ko-KR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/yuna.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/3.jpg'],
            ['id' => 3633, 'voice' => 'Enrique', 'voice_id' => 'es-ES_EnriqueV3Voice', 'gender' => 'Male', 'language_code' => 'es-ES', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/enrique.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/24.jpg'],
            ['id' => 3634, 'voice' => 'Laura', 'voice_id' => 'es-ES_LauraV3Voice', 'gender' => 'Female', 'language_code' => 'es-ES', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/laura.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/4.jpg'],
            ['id' => 3635, 'voice' => 'Sofia', 'voice_id' => 'es-LA_SofiaV3Voice', 'gender' => 'Female', 'language_code' => 'es-MX', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/sofia.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/5.jpg'],
            ['id' => 3636, 'voice' => 'Sofia', 'voice_id' => 'es-US_SofiaV3Voice', 'gender' => 'Female', 'language_code' => 'es-US', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/sofia-us.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/6.jpg'],
            
            ['id' => 3637, 'voice' => 'Alena', 'voice_id' => 'cs-CZ_AlenaVoice', 'gender' => 'Female', 'language_code' => 'cs-CZ', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/alena.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/7.jpg'],
            ['id' => 3638, 'voice' => 'Adele', 'voice_id' => 'nl-BE_AdeleVoice', 'gender' => 'Female', 'language_code' => 'nl-BE', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/adele.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/8.jpg'],
            ['id' => 3639, 'voice' => 'Bram', 'voice_id' => 'nl-BE_BramVoice', 'gender' => 'Male', 'language_code' => 'nl-BE', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/bram.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/25.jpg'],
            ['id' => 3640, 'voice' => 'Steve', 'voice_id' => 'en-AU_SteveVoice', 'gender' => 'Male', 'language_code' => 'en-AU', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/steve.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/26.jpg'],
            ['id' => 3641, 'voice' => 'Louise', 'voice_id' => 'fr-CA_LouiseV3Voice', 'gender' => 'Female', 'language_code' => 'fr-CA', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/louise.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/9.jpg'],
            ['id' => 3642, 'voice' => 'Isabela', 'voice_id' => 'pt-BR_IsabelaV3Voice', 'gender' => 'Female', 'language_code' => 'pt-BR', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/isabela.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/10.jpg'],
            ['id' => 3643, 'voice' => 'Ingrid', 'voice_id' => 'sv-SE_IngridVoice', 'gender' => 'Female', 'language_code' => 'sv-SE', 'vendor_id' => 'ibm_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/ibm/ingrid.mp3', 'status' => 'active' , 'vendor' => 'ibm', 'vendor_img' => '/img/csp/ibm-sm.png', 'avatar_url' => '/voices/ibm/avatars/11.jpg'],
        ];
    
        
        foreach ($voices as $voice) {
            Voice::updateOrCreate(['id' => $voice['id']], $voice);
        }
    }
}
